
services:
  db:
    image: postgres:15
    container_name: postgresql-paathshala
    restart: unless-stopped
    environment:
      POSTGRES_DB: paathshala-db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: paathshala-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin4.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8082:80"   # pgAdmin accessible on localhost:8082
    depends_on:
      - db

  app:
    build: .
    container_name: paathshala
    depends_on:
      - db
    ports:
      - "8081:8081"

    env_file:
      - .env


    #    environment:
    #      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/paathshala-db
    #      SPRING_DATASOURCE_USERNAME: myuser
    #      SPRING_DATASOURCE_PASSWORD: mypassword



    restart: unless-stopped

volumes:
  pgdata:
